"""add remediation columns to attempts, answers, chapter contents

Revision ID: 1a5d6e5d91ff
Revises: 97a1e1bb560c
Create Date: 2026-09-08 21:35:01.335746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a5d6e5d91ff'
down_revision: Union[str, Sequence[str], None] = '97a1e1bb560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_answers', sa.Column('misconception_tag', sa.String(length=255), nullable=True))
    op.add_column('assignment_attempts', sa.Column('verdict_reasoning', sa.Text(), nullable=True))
    op.add_column('chapter_contents', sa.Column('remediation_target_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chapter_contents', sa.Column('remediation_source_attempt_id', sa.Integer(), nullable=True))
    op.create_index('ix_chapter_contents_one_user_version_per_chapter', 'chapter_contents', ['chapter_id', 'user_id', 'version'], unique=True, postgresql_where=sa.text("scope = 'user'"))
    op.create_index('ix_chapter_contents_unique_remediation_source', 'chapter_contents', ['remediation_source_attempt_id'], unique=True, postgresql_where=sa.text('remediation_source_attempt_id IS NOT NULL'))
    op.create_foreign_key(None, 'chapter_contents', 'assignment_attempts', ['remediation_source_attempt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter_contents', type_='foreignkey')
    op.drop_index('ix_chapter_contents_unique_remediation_source', table_name='chapter_contents', postgresql_where=sa.text('remediation_source_attempt_id IS NOT NULL'))
    op.drop_index('ix_chapter_contents_one_user_version_per_chapter', table_name='chapter_contents', postgresql_where=sa.text("scope = 'user'"))
    op.drop_column('chapter_contents', 'remediation_source_attempt_id')
    op.drop_column('chapter_contents', 'remediation_target_tags')
    op.drop_column('assignment_attempts', 'verdict_reasoning')
    op.drop_column('assignment_answers', 'misconception_tag')
    # ### end Alembic commands ###
