"""add research notes to chapter contents

Revision ID: 359e8245c90d
Revises: 8978f10c6e25
Create Date: 2026-09-11 18:08:03.132872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359e8245c90d'
down_revision: Union[str, Sequence[str], None] = '8978f10c6e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_contents', sa.Column('research_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_contents', 'research_notes')
    # ### end Alembic commands ###
