"""add assignment_user_topups and assignment_questions.user_id

Revision ID: 3bbcbf9e6b23
Revises: 3c0d91d7f6a4
Create Date: 2026-09-09 11:28:58.585304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bbcbf9e6b23'
down_revision: Union[str, Sequence[str], None] = '3c0d91d7f6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_user_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'user_id', name='uq_assignment_user_topup')
    )
    op.create_index(op.f('ix_assignment_user_topups_assignment_id'), 'assignment_user_topups', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_user_topups_user_id'), 'assignment_user_topups', ['user_id'], unique=False)
    op.add_column('assignment_questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assignment_questions_user_id'), 'assignment_questions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'assignment_questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment_questions', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_questions_user_id'), table_name='assignment_questions')
    op.drop_column('assignment_questions', 'user_id')
    op.drop_index(op.f('ix_assignment_user_topups_user_id'), table_name='assignment_user_topups')
    op.drop_index(op.f('ix_assignment_user_topups_assignment_id'), table_name='assignment_user_topups')
    op.drop_table('assignment_user_topups')
    # ### end Alembic commands ###
