"""add course extension scope and job table

Revision ID: 6b8c344d0b07
Revises: c4652b1e9d01
Create Date: 2026-09-10 23:31:53.591534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b8c344d0b07'
down_revision: Union[str, Sequence[str], None] = 'c4652b1e9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_extension_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_extension_jobs_active', 'course_extension_jobs', ['course_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_course_extension_jobs_course_id'), 'course_extension_jobs', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_extension_jobs_user_id'), 'course_extension_jobs', ['user_id'], unique=False)
    op.add_column('chapters', sa.Column('scope', sa.String(length=16), nullable=False, server_default='global'))
    op.add_column('chapters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chapters_user_id'), 'chapters', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chapters', 'users', ['user_id'], ['id'])
    op.add_column('modules', sa.Column('scope', sa.String(length=16), nullable=False, server_default='global'))
    op.add_column('modules', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('ix_modules_one_user_bucket_per_course', 'modules', ['course_id', 'user_id'], unique=True, postgresql_where=sa.text("scope = 'user'"))
    op.create_index(op.f('ix_modules_user_id'), 'modules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'modules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # drop the partial unique indexes before their columns disappear
    op.drop_index('ix_modules_one_user_bucket_per_course', table_name='modules', postgresql_where=sa.text("scope = 'user'"))
    op.drop_index('ix_course_extension_jobs_active', table_name='course_extension_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    # dropping the columns removes their single-column indexes and FK constraints
    op.drop_column('modules', 'user_id')
    op.drop_column('modules', 'scope')
    op.drop_column('chapters', 'user_id')
    op.drop_column('chapters', 'scope')
    op.drop_table('course_extension_jobs')
