"""add course extension scope and job table

Revision ID: 6b8c344d0b07
Revises: c4652b1e9d01
Create Date: 2026-09-10 23:31:53.591534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b8c344d0b07'
down_revision: Union[str, Sequence[str], None] = 'c4652b1e9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_extension_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_extension_jobs_active', 'course_extension_jobs', ['course_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_course_extension_jobs_course_id'), 'course_extension_jobs', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_extension_jobs_user_id'), 'course_extension_jobs', ['user_id'], unique=False)
    op.add_column('chapters', sa.Column('scope', sa.String(length=16), nullable=False))
    op.add_column('chapters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chapters_user_id'), 'chapters', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chapters', 'users', ['user_id'], ['id'])
    op.add_column('modules', sa.Column('scope', sa.String(length=16), nullable=False))
    op.add_column('modules', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('ix_modules_one_user_bucket_per_course', 'modules', ['course_id', 'user_id'], unique=True, postgresql_where=sa.text("scope = 'user'"))
    op.create_index(op.f('ix_modules_user_id'), 'modules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'modules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_index(op.f('ix_modules_user_id'), table_name='modules')
    op.drop_index('ix_modules_one_user_bucket_per_course', table_name='modules', postgresql_where=sa.text("scope = 'user'"))
    op.drop_column('modules', 'user_id')
    op.drop_column('modules', 'scope')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_index(op.f('ix_chapters_user_id'), table_name='chapters')
    op.drop_column('chapters', 'user_id')
    op.drop_column('chapters', 'scope')
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_course_extension_jobs_user_id'), table_name='course_extension_jobs')
    op.drop_index(op.f('ix_course_extension_jobs_course_id'), table_name='course_extension_jobs')
    op.drop_index('ix_course_extension_jobs_active', table_name='course_extension_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('course_extension_jobs')
    # ### end Alembic commands ###
