"""add composite assignment attempt index

Revision ID: 724e19ace4b5
Revises: 359e8245c90d
Create Date: 2026-09-13 20:27:15.612409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724e19ace4b5'
down_revision: Union[str, Sequence[str], None] = '359e8245c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assignment_attempts_assignment_user_status_created', 'assignment_attempts', ['assignment_id', 'user_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_attempts_assignment_user_status_created', table_name='assignment_attempts')
    # ### end Alembic commands ###
