"""add assignment_attempts and assignment_answers tables

Revision ID: 87240617ce40
Revises: f3cb11748c20
Create Date: 2026-09-08 12:25:35.546514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87240617ce40'
down_revision: Union[str, Sequence[str], None] = 'f3cb11748c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_attempts_assignment_id'), 'assignment_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_attempts_user_id'), 'assignment_attempts', ['user_id'], unique=False)
    op.create_table('assignment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('concept_tag', sa.String(length=255), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['assignment_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assignment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_answers_attempt_id'), 'assignment_answers', ['attempt_id'], unique=False)
    op.create_index('ix_assignment_answers_unique_per_attempt', 'assignment_answers', ['attempt_id', 'question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_answers_unique_per_attempt', table_name='assignment_answers')
    op.drop_index(op.f('ix_assignment_answers_attempt_id'), table_name='assignment_answers')
    op.drop_table('assignment_answers')
    op.drop_index(op.f('ix_assignment_attempts_user_id'), table_name='assignment_attempts')
    op.drop_index(op.f('ix_assignment_attempts_assignment_id'), table_name='assignment_attempts')
    op.drop_table('assignment_attempts')
    # ### end Alembic commands ###
