"""add export and generation job tables

Revision ID: 8978f10c6e25
Revises: 6b8c344d0b07
Create Date: 2026-09-11 11:13:30.520369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8978f10c6e25'
down_revision: Union[str, Sequence[str], None] = '6b8c344d0b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('completed_units', sa.Integer(), nullable=False),
    sa.Column('unit_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_generation_runs_course_id'), 'course_generation_runs', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_generation_runs_user_id'), 'course_generation_runs', ['user_id'], unique=False)
    op.create_index('ix_generation_runs_active', 'course_generation_runs', ['course_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_key', sa.String(length=512), nullable=True),
    sa.Column('result_size', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_course_id'), 'export_jobs', ['course_id'], unique=False)
    op.create_index('ix_export_jobs_user_course', 'export_jobs', ['user_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_user_id'), 'export_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_jobs_user_id'), table_name='export_jobs')
    op.drop_index('ix_export_jobs_user_course', table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_course_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index('ix_generation_runs_active', table_name='course_generation_runs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_course_generation_runs_user_id'), table_name='course_generation_runs')
    op.drop_index(op.f('ix_course_generation_runs_course_id'), table_name='course_generation_runs')
    op.drop_table('course_generation_runs')
    # ### end Alembic commands ###
