"""persist remediation dispatch state on attempts

Revision ID: b98e46d4518f
Revises: 724e19ace4b5
Create Date: 2026-09-13 20:35:23.265533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98e46d4518f'
down_revision: Union[str, Sequence[str], None] = '724e19ace4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_attempts', sa.Column('remediation_concept_tags', sa.JSON(), nullable=True))
    op.add_column('assignment_attempts', sa.Column('remediation_dispatched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_attempts', 'remediation_dispatched_at')
    op.drop_column('assignment_attempts', 'remediation_concept_tags')
    # ### end Alembic commands ###
