"""add course schema tables

Revision ID: d11f8c188659
Revises: 95d7794d4306
Create Date: 2026-09-07 15:15:57.770698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd11f8c188659'
down_revision: Union[str, Sequence[str], None] = '95d7794d4306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before any table below uses the `vector` column type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_slug', sa.String(length=255), nullable=False),
    sa.Column('topic_raw', sa.Text(), nullable=False),
    sa.Column('topic_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_topic_slug'), 'courses', ['topic_slug'], unique=True)
    op.create_table('course_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_slug', sa.String(length=255), nullable=False),
    sa.Column('topic_raw', sa.Text(), nullable=False),
    sa.Column('topic_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_jobs_active_topic_slug', 'course_jobs', ['topic_slug'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_course_jobs_topic_slug'), 'course_jobs', ['topic_slug'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_module_id'), 'chapters', ['module_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_chapter_id'), 'concepts', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_concepts_course_id'), 'concepts', ['course_id'], unique=False)
    op.create_table('concept_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_edges_concept_id'), 'concept_edges', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_edges_prerequisite_concept_id'), 'concept_edges', ['prerequisite_concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_edges_prerequisite_concept_id'), table_name='concept_edges')
    op.drop_index(op.f('ix_concept_edges_concept_id'), table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_concepts_course_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_chapter_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_chapters_module_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_course_jobs_topic_slug'), table_name='course_jobs')
    op.drop_index('ix_course_jobs_active_topic_slug', table_name='course_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('course_jobs')
    op.drop_index(op.f('ix_courses_topic_slug'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
