"""add assignments and assignment_questions tables

Revision ID: f3cb11748c20
Revises: 1027ae63941c
Create Date: 2026-09-08 10:30:24.740221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3cb11748c20'
down_revision: Union[str, Sequence[str], None] = '1027ae63941c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('chapter_content_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(level = 'chapter' AND chapter_content_id IS NOT NULL AND module_id IS NULL) OR (level = 'module' AND module_id IS NOT NULL AND chapter_content_id IS NULL)", name='ck_assignments_level_target'),
    sa.ForeignKeyConstraint(['chapter_content_id'], ['chapter_contents.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_chapter_content_id'), 'assignments', ['chapter_content_id'], unique=False)
    op.create_index(op.f('ix_assignments_module_id'), 'assignments', ['module_id'], unique=False)
    op.create_index('ix_assignments_one_global_per_chapter_content', 'assignments', ['chapter_content_id'], unique=True, postgresql_where=sa.text("scope = 'global' AND level = 'chapter'"))
    op.create_index('ix_assignments_one_global_per_module', 'assignments', ['module_id'], unique=True, postgresql_where=sa.text("scope = 'global' AND level = 'module'"))
    op.create_index('ix_assignments_one_user_per_chapter_content', 'assignments', ['chapter_content_id', 'user_id'], unique=True, postgresql_where=sa.text("scope = 'user' AND level = 'chapter'"))
    op.create_index('ix_assignments_one_user_per_module', 'assignments', ['module_id', 'user_id'], unique=True, postgresql_where=sa.text("scope = 'user' AND level = 'module'"))
    op.create_table('assignment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('concept_tag', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('source_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['source_section_id'], ['chapter_content_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_questions_assignment_id'), 'assignment_questions', ['assignment_id'], unique=False)
    op.create_index('ix_assignment_questions_unique_order', 'assignment_questions', ['assignment_id', 'order'], unique=True)
    # NOTE: autogenerate also proposed dropping checkpoint_writes/checkpoint_blobs/
    # checkpoints/checkpoint_migrations. Those tables are managed by LangGraph's
    # Postgres checkpointer (app/agents/course_creation/checkpointer.py), not by
    # our SQLAlchemy models, so they never appear in Base.metadata — that's a
    # known false positive, not a real schema change. Left out deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_questions_unique_order', table_name='assignment_questions')
    op.drop_index(op.f('ix_assignment_questions_assignment_id'), table_name='assignment_questions')
    op.drop_table('assignment_questions')
    op.drop_index('ix_assignments_one_user_per_module', table_name='assignments', postgresql_where=sa.text("scope = 'user' AND level = 'module'"))
    op.drop_index('ix_assignments_one_user_per_chapter_content', table_name='assignments', postgresql_where=sa.text("scope = 'user' AND level = 'chapter'"))
    op.drop_index('ix_assignments_one_global_per_module', table_name='assignments', postgresql_where=sa.text("scope = 'global' AND level = 'module'"))
    op.drop_index('ix_assignments_one_global_per_chapter_content', table_name='assignments', postgresql_where=sa.text("scope = 'global' AND level = 'chapter'"))
    op.drop_index(op.f('ix_assignments_module_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_chapter_content_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
